AllCops:
  DisabledByDefault: true
  NewCops: disable

Bundler/DuplicatedGem:
  Enabled: true

Gemspec/DuplicatedAssignment:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/ShadowedArgument:
  Enabled: true

# Lint/ShadowedException:
#   Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/Syntax:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true
